name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:

  bandit_scan:
    name: Bandit SAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: |
          bandit -r . -f json -o sast-bandit.json -ll || true

      - name: Upload Bandit results
        uses: actions/upload-artifact@v4
        with:
          name: bandit-results
          path: sast-bandit.json


  semgrep_scan:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          semgrep scan --severity=ERROR --severity=WARNING --json --output=sast-semgrep.json || true

      - name: Upload Semgrep results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: sast-semgrep.json


  docker_build_scan:
    name: Build & Scan Docker Image
    runs-on: ubuntu-latest
    needs: [bandit_scan, semgrep_scan]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t pygoat-app .

      - name: Docker Scout Scan
        uses: docker/scout-action@v1
        with:
          command: quickview
          image: pygoat-app
          continue-on-error: true
